# This is a basic workflow to help you get started with Actions

name: Deployment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      # Runs a single command using the runners shell
      - name: setup git authentication 
        run: |
          git config --global user.email "joey.baruch@gmail.com"
          git config --global user.name "Joey Baruch (publish workflow)"
      
      - name: publish
        run: |
          yarn
          npm run deploy
        env:
          REACT_APP_API_BASEURL: https://marketx-backend-joey.herokuapp.com
